server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

# application.yml

spring:
  profiles:
    active: dev  # default application 파일의 이름
                 # ex application-dev.yml -> dev
  jackson:
    property-naming-strategy: SNAKE_CASE

cloud:
  aws:
    s3:
      bucket: kupica-img
      bucket-url: https://kupica-img.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: AKIASR6SI6SWOLISQ55H
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


file:
  path: C:/project-kupica/