spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/photogram?serverTimezone=Asia/Seoul
    username:
    password:
  mvc:
    view:
      suffix: .html

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: com.litaa.projectkupica.config.SnakeCasePhysicalNameStrategy
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
    generate-ddl: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

  security:
    user:
      name: test
      password: 1234

