server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

file:
   path: C:/photogram/images/