spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/photogram?serverTimezone=Asia/Seoul
    username: zoso
    password: zoso2513
  mvc:
    view:
      suffix: .html

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: com.litaa.projectkupica.config.SnakeCasePhysicalNameStrategy
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: false
    generate-ddl: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB


  security:
    user:
      name: test
      password: 1234

  config:
    import: dev-env.properties

server:
  tomcat:
    max-http-form-post-size: 20MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
      bucket-url: ${S3_BUCKET_URL}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    cloudfront-domain: ${CLOUDFRONT_DOMAIN}


