server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

# application.yml

spring:
  profiles:
    active: dev  # default application 파일의 이름
                 # ex application-dev.yml -> dev
  jackson:
    property-naming-strategy: SNAKE_CASE

cloud:
  aws:
    s3:
      bucket: kupica-img
      bucket-url: 
    credentials:
<<<<<<< Updated upstream
      access-key: 
      secret-key: 
=======
      access-key:
      secret-key:
>>>>>>> Stashed changes
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
